-- Espelho dev de rj-segovi.adm_central_atendimento_1746.chamado
CREATE TABLE IF NOT EXISTS `rj-crm-registry-dev.dev__dev_fantasma__adm_central_atendimento_1746.chamado`
(
    id_chamado STRING,
    id_origem_ocorrencia STRING,
    data_inicio DATETIME,
    data_fim DATETIME,
    id_bairro STRING,
    id_territorialidade STRING,
    id_logradouro STRING,
    numero_logradouro INT64,
    id_unidade_organizacional STRING,
    nome_unidade_organizacional STRING,
    id_unidade_organizacional_mae STRING,
    unidade_organizacional_ouvidoria STRING,
    categoria STRING,
    id_tipo STRING,
    tipo STRING,
    id_subtipo STRING,
    subtipo STRING,
    status STRING,
    longitude FLOAT64,
    latitude FLOAT64,
    data_alvo_finalizacao DATETIME,
    data_alvo_diagnostico DATETIME,
    data_real_diagnostico DATETIME,
    tempo_prazo INT64,
    prazo_unidade STRING,
    prazo_tipo STRING,
    dentro_prazo STRING,
    situacao STRING,
    tipo_situacao STRING,
    justificativa_status STRING,
    reclamacoes INT64,
    descricao STRING,
    extracted_at TIMESTAMP,
    updated_at STRING,
    data_particao DATE
);
