-- Espelho dev de rj-segovi.adm_central_atendimento_1746.pessoa
CREATE TABLE IF NOT EXISTS `rj-crm-registry-dev.dev__dev_fantasma__adm_central_atendimento_1746.pessoa`
(
    id_pessoa INT64,
    cpf STRING,
    nome STRING,
    documento_identidade STRING,
    numero_matricula STRING,
    nome_mae STRING,
    data_nascimento DATE,
    sexo STRING,
    atividade_profissional STRING,
    id_cargo INT64,
    id_idioma INT64,
    id_pais_ddi INT64,
    id_tratamento INT64,
    id_escolaridade INT64,
    id_tipo_endereco INT64,
    id_bairro_logradouro INT64,
    id_unidade_organizacional INT64,
    email STRING,
    telefone_1 STRING,
    telefone_2 STRING,
    telefone_3 STRING,
    endereco STRING,
    endereco_numero INT64,
    endereco_cep STRING,
    endereco_complemento STRING,
    endereco_referencia STRING,
    coordenada_x FLOAT64,
    coordenada_y FLOAT64,
    flag_ativo STRING,
    flag_auditor STRING,
    flag_sms STRING,
    flag_email STRING,
    flag_recebe_sms STRING,
    flag_recebe_email STRING,
    flag_reintegracao_sms STRING,
    flag_reintegracao_email STRING,
    flag_nao_reside_no_municipio STRING,
    flag_recebe_notificacao_generica STRING,
    flag_recebe_notificacao_alerta_rio STRING,
    flag_recebe_notificacao_andamento_chamado STRING,
    data_insercao DATETIME,
    data_atualizacao DATETIME,
    extracted_at TIMESTAMP
);
