BEGIN
  EXECUTE IMMEDIATE 'GRANT SELECT ON "$schema"."$table" TO RL_NFSE';
  EXECUTE IMMEDIATE 'GRANT SELECT ON "$schema"."$table" TO RL_NFSE_SIGA';
  EXECUTE IMMEDIATE 'GRANT SELECT ON "$schema"."$table" TO RL_NFSEOWNER_DRL';
  EXECUTE IMMEDIATE 'GRANT SELECT, ALTER, DELETE ON "$schema"."$table" TO NFSE_OWNER';
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM NFSE_SIGA."$table" FOR "$schema"."$table"';
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM NFSE_USER."$table" FOR "$schema"."$table"';
END;
