name: rj_sme__brutos_gestao_escolar
prefect-version: 3.4.3

build:
  - prefect.deployments.steps.run_shell_script:
      id: get-commit-hash
      script: git rev-parse --short HEAD
      stream_output: false
  - prefect_docker.deployments.steps.build_docker_image:
      id: build-image
      requires: prefect-docker>=0.6.5
      image_name: ghcr.io/prefeitura-rio/prefect_rj_iplanrio/deployments
      tag: "rj_sme__brutos_gestao_escolar-{{ get-commit-hash.stdout }}"
      dockerfile: pipelines/rj_sme__brutos_gestao_escolar/Dockerfile

push:
  - prefect_docker.deployments.steps.push_docker_image:
      requires: prefect-docker>=0.6.5
      image_name: "{{ build-image.image_name }}"
      tag: "{{ build-image.tag }}"

pull:
  - prefect.deployments.steps.set_working_directory:
      directory: /opt/prefect/prefect_rj_iplanrio

deployments:
  - name: rj-sme--brutos_gestao_escolar--staging
    version: "{{ build-image.tag }}"
    entrypoint: pipelines/rj_sme__brutos_gestao_escolar/flow.py:rj_sme__brutos_gestao_escolar
    work_pool:
      name: datario-pool
      work_queue_name: default
      job_variables:
        image: "{{ build-image.image_name }}:{{ build-image.tag }}"
        command: uv run --package rj_sme__brutos_gestao_escolar -- prefect flow-run execute
        image_pull_policy: Always
  - name: rj-sme--brutos_gestao_escolar--prod
    version: "{{ get-commit-hash.stdout }}"
    entrypoint: pipelines/rj_sme__brutos_gestao_escolar/flow.py:rj_sme__brutos_gestao_escolar
    work_pool:
      name: datario-pool
      work_queue_name: default
      job_variables:
        image: "{{ build-image.image_name }}:{{ build-image.tag }}"
        command: uv run --package rj_sme__brutos_gestao_escolar -- prefect flow-run execute
        image_pull_policy: Always
    schedules:
      - interval: 86400
        anchor_date: "2022-01-01T02:30:00"
        timezone: America/Sao_Paulo
        slug: turma
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: turma
          dump_mode: append
          partition_columns: Ano
          partition_date_format: "%Y"
          break_query_frequency: year
          break_query_start: current_year
          break_query_end: current_year
          add_timestamp_column: true
          execute_query: |
            SELECT
                Ano, Curso, Nivel_Ensino,
                Modalidade, Grupamento, Turma,
                Turno, Sala, Area_Sala, Capac_Sala,
                Tipo_Sala, Sala_Util_Como, Tot_Turma,
                tur_id, esc_id, dep_id
            FROM GestaoEscolar.dbo.VW_BI_Turma

      - interval: 86400
        anchor_date: "2022-01-01T02:32:00"
        timezone: America/Sao_Paulo
        slug: CLS_TurmaAulaAluno
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: CLS_TurmaAulaAluno
          dump_mode: append
          partition_columns: taa_dataAlteracao_converted
          partition_date_format: "%Y-%m-%d"
          break_query_frequency: day
          break_query_start: current_day
          break_query_end: current_day
          execute_query: |
            SELECT
                tud_id,
                tau_id,
                alu_id,
                mtu_id,
                mtd_id,
                taa_frequencia,
                taa_situacao,
                taa_dataCriacao,
                taa_dataAlteracao,
                CONVERT(date, taa_dataAlteracao) AS taa_dataAlteracao_converted,
                taa_anotacao,
                taa_frequenciaBitMap,
                usu_idDocenteAlteracao,
                GETDATE() AS loaded_at
            FROM GestaoEscolar.dbo.CLS_TurmaAulaAluno
      - interval: 86400
        anchor_date: "2022-01-01T02:34:00"
        timezone: America/Sao_Paulo
        slug: diasCoc
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: diasCoc
          dump_mode: overwrite
          execute_query: |
            select distinct cal.cal_id,
                            tpc_id,
                            dbo.FN_CalcularDiasUteis(cap_dataInicio,cap_dataFim,'8BB1DECA-BB19-E011-87E8-E61F133BFC53',
                            cal.cal_id) diasCoc,
                            GETDATE() AS loaded_at
            from ACA_CalendarioPeriodo cap WITH(NOLOCK)
            INNER JOIN ACA_CalendarioAnual          CAL WITH(NOLOCK) ON CAL.cal_id = cap.cal_id and cal_situacao <> 3
            inner join MTR_ProcessoFechamentoInicio pfi WITH(NOLOCK) ON pfi.pfi_anoInicio = cal.cal_ano and pfi_situacao <> 3 and pfi_AnoLetivoCorrente = 1
      - interval: 86400
        anchor_date: "2022-01-01T02:36:00"
        timezone: America/Sao_Paulo
        slug: numeroDeAulasCte
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: numeroDeAulasCte
          dump_mode: overwrite
          execute_query: |
            SELECT
                     MTU.alu_id,
                     MTU.mtu_id,
                     CAP.tpc_id,
                     GestaoEscolar.dbo.FN_CalcularDiasUteis(CAP.cap_dataInicio,GETDATE(),'8BB1DECA-BB19-E011-87E8-E61F133BFC53',CAP.cal_id) * ISNULL(CRP.crp_qtdeTemposDia,1) numeroAulas,
                     GETDATE() AS loaded_at
             FROM MTR_MatriculaTurma MTU WITH(NOLOCK)
                 INNER JOIN TUR_Turma TUR WITH(NOLOCK)
                     ON MTU.tur_id = TUR.tur_id
                     AND TUR.tur_situacao IN (1,5)
                 INNER JOIN ACA_CalendarioAnual CAL WITH(NOLOCK)
                     ON TUR.cal_id = CAL.cal_id
                     AND CAL.cal_ano = YEAR(GETDATE())
                 INNER JOIN TUR_TurmaCurriculo TCR WITH(NOLOCK)
                     ON TUR.tur_id = TCR.tur_id
                     AND TCR.tcr_situacao = 1
                 INNER JOIN ACA_CurriculoPeriodo CRP WITH(NOLOCK)
                     ON TCR.cur_id = CRP.cur_id
                     AND TCR.crr_id = CRP.crr_id
                     AND TCR.crp_id = CRP.crp_id
                     AND CRP.crp_situacao = 1
                 INNER JOIN ACA_CalendarioPeriodo CAP WITH(NOLOCK)
                     ON TUR.cal_id = CAP.cal_id
                     AND GETDATE() BETWEEN CAP.cap_dataInicio AND CAP.cap_dataFim
      - interval: 86400
        anchor_date: "2022-01-01T02:38:00"
        timezone: America/Sao_Paulo
        slug: CLS_AlunoAvaliacaoTurma
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: CLS_AlunoAvaliacaoTurma
          dump_mode: append
          partition_columns: aat_dataAlteracao_converted
          partition_date_format: "%Y-%m-%d"
          break_query_frequency: month
          break_query_start: current_month
          break_query_end: current_month
          execute_query: |
            SELECT  tur_id,
                    alu_id,
                    mtu_id,
                    aat_id,
                    fav_id,
                    ava_id,
                    aat_avaliacao,
                    aat_frequencia,
                    aat_comentarios,
                    aat_relatorio,
                    aat_situacao,
                    aat_dataCriacao,
                    aat_dataAlteracao,
                    CONVERT(date, aat_dataAlteracao) AS aat_dataAlteracao_converted,
                    aat_semProfessor,
                    aat_numeroFaltas,
                    aat_numeroAulas,
                    arq_idRelatorio,
                    aat_ausenciasCompensadas,
                    aat_avaliacaoAdicional,
                    aat_faltoso,
                    aat_frequenciaAcumulada,
                    aat_registroexterno,
                    aat_frequenciaAcumuladaCalculada,
                    aat_naoAvaliado,
                    aat_avaliacaoPosConselho,
                    aat_justificativaPosConselho,
                    aat_frequenciaFinalAjustada,
                    GETDATE() AS loaded_at
            FROM GestaoEscolar.dbo.CLS_AlunoAvaliacaoTurma

