name: rj_sme__brutos_core_sso
prefect-version: 3.4.3

build:
  - prefect.deployments.steps.run_shell_script:
      id: get-commit-hash
      script: git rev-parse --short HEAD
      stream_output: false
  - prefect_docker.deployments.steps.build_docker_image:
      id: build-image
      requires: prefect-docker>=0.6.5
      image_name: ghcr.io/prefeitura-rio/prefect_rj_iplanrio/deployments
      tag: "rj_sme__brutos_core_sso-{{ get-commit-hash.stdout }}"
      dockerfile: pipelines/rj_sme__brutos_core_sso/Dockerfile

push:
  - prefect_docker.deployments.steps.push_docker_image:
      requires: prefect-docker>=0.6.5
      image_name: "{{ build-image.image_name }}"
      tag: "{{ build-image.tag }}"

pull:
  - prefect.deployments.steps.set_working_directory:
      directory: /opt/prefect/prefect_rj_iplanrio

deployments:
  - name: rj-sme--brutos_core_sso--staging
    version: "{{ build-image.tag }}"
    entrypoint: pipelines/rj_sme__brutos_core_sso/flow.py:rj_sme__brutos_core_sso
    work_pool:
      name: k3s-pool
      work_queue_name: default
      job_variables:
        image: "{{ build-image.image_name }}:{{ build-image.tag }}"
        command: uv run --package rj_sme__brutos_core_sso -- prefect flow-run execute
        image_pull_policy: Always
  - name: rj-sme--brutos_core_sso--prod
    version: "{{ get-commit-hash.stdout }}"
    entrypoint: pipelines/rj_sme__brutos_core_sso/flow.py:rj_sme__brutos_core_sso
    work_pool:
      name: k3s-pool
      work_queue_name: default
      job_variables:
        image: "{{ build-image.image_name }}:{{ build-image.tag }}"
        command: uv run --package rj_sme__brutos_core_sso -- prefect flow-run execute
        image_pull_policy: Always
    schedules:
      - interval: 86400
        anchor_date: "2022-01-01T02:40:00"
        timezone: America/Sao_Paulo
        slug: SYS_Entidade
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: SYS_Entidade
          dump_mode: overwrite
          execute_query: |
            SELECT  ent_id,
                    ten_id,
                    ent_codigo,
                    ent_nomeFantasia,
                    ent_razaoSocial,
                    ent_sigla,
                    ent_cnpj,
                    ent_inscricaoMunicipal,
                    ent_inscricaoEstadual,
                    ent_idSuperior,
                    ent_situacao,
                    ent_dataCriacao,
                    ent_dataAlteracao,
                    ent_integridade,
                    GETDATE() AS loaded_at
            FROM CoreSSO.dbo.SYS_Entidade;
      - interval: 86400
        anchor_date: "2022-01-01T02:42:00"
        timezone: America/Sao_Paulo
        slug: SYS_DiaNaoUtil
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: SYS_DiaNaoUtil
          dump_mode: overwrite
          execute_query: |
            SELECT  dnu_id,
                    dnu_nome,
                    dnu_abrangencia,
                    dnu_descricao,
                    dnu_data,
                    dnu_recorrencia,
                    dnu_vigenciaInicio,
                    dnu_vigenciaFim,
                    cid_id, unf_id,
                    dnu_situacao,
                    dnu_dataCriacao,
                    dnu_dataAlteracao,
                    GETDATE() AS loaded_at
            FROM CoreSSO.dbo.SYS_DiaNaoUtil;
      - interval: 86400
        anchor_date: "2022-01-01T02:44:00"
        timezone: America/Sao_Paulo
        slug: SYS_EntidadeEndereco
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: SYS_EntidadeEndereco
          dump_mode: overwrite
          execute_query: |
            SELECT  ent_id,
                    ene_id,
                    end_id,
                    ene_numero,
                    ene_complemento,
                    ene_situacao,
                    ene_dataCriacao,
                    ene_dataAlteracao
            FROM CoreSSO.dbo.SYS_EntidadeEndereco;
      - interval: 86400
        anchor_date: "2022-01-01T02:46:00"
        timezone: America/Sao_Paulo
        slug: END_Endereco
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: END_Endereco
          dump_mode: overwrite
          execute_query: |
            SELECT  end_id,
                    end_cep,
                    end_logradouro,
                    end_bairro,
                    end_distrito,
                    end_zona,
                    cid_id,
                    end_situacao,
                    end_dataCriacao,
                    end_dataAlteracao,
                    end_integridade
            FROM CoreSSO.dbo.END_Endereco;
      - interval: 86400
        anchor_date: "2022-01-01T02:48:00"
        timezone: America/Sao_Paulo
        slug: END_Cidade
        parameters:
          biglake_table: true
          batch_size: 50000
          table_id: END_Cidade
          dump_mode: overwrite
          execute_query: |
            SELECT  cid_id,
                    pai_id,
                    unf_id,
                    cid_nome,
                    cid_ddd,
                    cid_situacao,
                    cid_integridade
            FROM CoreSSO.dbo.END_Cidade;
