FROM ghcr.io/prefeitura-rio/prefect_rj_iplanrio/base:latest

RUN mkdir /opt/prefect/prefect_rj_iplanrio/pipelines/rj_sec__example

COPY ./pipelines/rj_sec__example /opt/prefect/prefect_rj_iplanrio/pipelines/
