# -*- coding: utf-8 -*-
"""
Schemas BigQuery das tabelas da pipeline Salesforce Data Cloud — só dados.
Cobre todas as tabelas de tabelas.yaml (final + _staging de cada uma).

Quem cria as tabelas é tasks/bigquery.py:ensure_bq_tables (a cada execução,
idempotente); load_chunk_to_staging usa SCHEMAS pro schema da carga.
"""

from __future__ import annotations

from google.cloud import bigquery

_TIMESTAMP = bigquery.enums.SqlTypeNames.TIMESTAMP
_STRING = bigquery.enums.SqlTypeNames.STRING
_DATE = bigquery.enums.SqlTypeNames.DATE
_FLOAT64 = bigquery.enums.SqlTypeNames.FLOAT64
_BOOL = bigquery.enums.SqlTypeNames.BOOLEAN


def _base_fields(extra: list[bigquery.SchemaField]) -> list[bigquery.SchemaField]:
    """Adiciona _loaded_at e data_particao ao final de qualquer schema."""
    return extra + [
        bigquery.SchemaField("_loaded_at", _TIMESTAMP),
        bigquery.SchemaField("data_particao", _DATE),
    ]


# --- Eventos WhatsApp (DLL MessagingEventsWhatsAppV2_00Das_4CAB1BC2__dll) ---
# Nomes = saída de _clean_dc_field_name (transform.py) sobre as colunas de
# sql/messaging_events_whatsapp.sql. Chave do MERGE: event_id (EventId__c —
# conferido único e nunca vazio no histórico todo em 2026-09-29).
_MESSAGING_EVENTS_WHATSAPP_FIELDS = [
    bigquery.SchemaField("event_id", _STRING),
    bigquery.SchemaField("event_date_time", _TIMESTAMP),
    bigquery.SchemaField("event_type", _STRING),
    bigquery.SchemaField("send_status", _STRING),
    bigquery.SchemaField("not_sent_reason", _STRING),
    bigquery.SchemaField("error_code", _STRING),
    bigquery.SchemaField("contact_point_phone_number", _STRING),
    bigquery.SchemaField("individual_id", _STRING),
    bigquery.SchemaField("kq_individual_id", _STRING),
    bigquery.SchemaField("whats_app_wam_id", _STRING),
    bigquery.SchemaField("message_id", _STRING),
    bigquery.SchemaField("bulk_message_id", _STRING),
    bigquery.SchemaField("content_id", _STRING),
    bigquery.SchemaField("message", _STRING),
    bigquery.SchemaField("message_purpose", _STRING),
    bigquery.SchemaField("pricing_category", _STRING),
    bigquery.SchemaField("journey_id", _STRING),
    bigquery.SchemaField("flow_element_run_id", _STRING),
    bigquery.SchemaField("kq_flow_element_run_id", _STRING),
    bigquery.SchemaField("kq_event_id", _STRING),
    bigquery.SchemaField("engagement_channel", _STRING),
    bigquery.SchemaField("kq_engagement_channel", _STRING),
    bigquery.SchemaField("application", _STRING),
    bigquery.SchemaField("source", _STRING),
    bigquery.SchemaField("sender_id", _STRING),
    bigquery.SchemaField("sender_display_name", _STRING),
    bigquery.SchemaField("username", _STRING),
    bigquery.SchemaField("business_unit_id", _STRING),
    bigquery.SchemaField("external_account_id", _STRING),
    bigquery.SchemaField("tenant", _STRING),
    bigquery.SchemaField("bsuid", _STRING),
    bigquery.SchemaField("parent_bsuid", _STRING),
    bigquery.SchemaField("ctwa_campaign_source_type", _STRING),
    bigquery.SchemaField("ctwa_campaign_source_id", _STRING),
    bigquery.SchemaField("ctwa_click_id", _STRING),
    bigquery.SchemaField("link_url", _STRING),
    bigquery.SchemaField("resolved_url", _STRING),
    bigquery.SchemaField("user_agent", _STRING),
    bigquery.SchemaField("global_event", _BOOL),
    bigquery.SchemaField("data_source", _STRING),
    bigquery.SchemaField("data_source_object", _STRING),
    bigquery.SchemaField("cdp_sys_source_version", _STRING),
    bigquery.SchemaField("cdp_sys_partition_date", _TIMESTAMP),
]

# ---------------------------------------------------------------------------
# Schemas por tabela
# ---------------------------------------------------------------------------

SCHEMAS: dict[str, list[bigquery.SchemaField]] = {
    # --- Agentforce (STDM) ---
    "ai_agent_session": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("related_messaging_session_id", _STRING),
        bigquery.SchemaField("ai_agent_channel_type", _STRING),
        bigquery.SchemaField("ai_agent_session_end_type", _STRING),
        bigquery.SchemaField("session_owner_id", _STRING),
        bigquery.SchemaField("session_owner_object", _STRING),
        bigquery.SchemaField("individual_id", _STRING),
        bigquery.SchemaField("previous_session_id", _STRING),
        bigquery.SchemaField("start_timestamp", _TIMESTAMP),
        bigquery.SchemaField("end_timestamp", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("external_source_id", _STRING),
        bigquery.SchemaField("variable_text", _STRING),
    ]),
    "ai_agent_interaction": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("ai_agent_session_id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_type", _STRING),
        bigquery.SchemaField("topic_api_name", _STRING),
        bigquery.SchemaField("session_owner_id", _STRING),
        bigquery.SchemaField("session_owner_object", _STRING),
        bigquery.SchemaField("individual_id", _STRING),
        bigquery.SchemaField("telemetry_trace_id", _STRING),
        bigquery.SchemaField("telemetry_trace_span_id", _STRING),
        bigquery.SchemaField("prev_interaction_id", _STRING),
        bigquery.SchemaField("start_timestamp", _TIMESTAMP),
        bigquery.SchemaField("end_timestamp", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("external_source_id", _STRING),
        bigquery.SchemaField("attribute_text", _STRING),
    ]),
    "ai_agent_interaction_step": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_step_type", _STRING),
        bigquery.SchemaField("name", _STRING),
        bigquery.SchemaField("telemetry_trace_span_id", _STRING),
        bigquery.SchemaField("gen_ai_gateway_request_id", _STRING),
        bigquery.SchemaField("gen_ai_gateway_response_id", _STRING),
        bigquery.SchemaField("generation_id", _STRING),
        bigquery.SchemaField("prev_step_id", _STRING),
        bigquery.SchemaField("start_timestamp", _TIMESTAMP),
        bigquery.SchemaField("end_timestamp", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("external_source_id", _STRING),
        bigquery.SchemaField("pre_step_variable_text", _STRING),
        bigquery.SchemaField("post_step_variable_text", _STRING),
        bigquery.SchemaField("attribute_text", _STRING),
        bigquery.SchemaField("error_message_text", _STRING),
        bigquery.SchemaField("sub_type", _STRING),
        bigquery.SchemaField("output_value_text", _STRING),
    ]),
    "ai_agent_interaction_message": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_id", _STRING),
        bigquery.SchemaField("ai_agent_session_id", _STRING),
        bigquery.SchemaField("ai_agent_session_participant_id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_message_type", _STRING),
        bigquery.SchemaField("ai_agent_interaction_msg_content_type", _STRING),
        bigquery.SchemaField("session_owner_id", _STRING),
        bigquery.SchemaField("individual_id", _STRING),
        bigquery.SchemaField("parent_message_id", _STRING),
        bigquery.SchemaField("content_text", _STRING),
        bigquery.SchemaField("message_sent_timestamp", _TIMESTAMP),
        bigquery.SchemaField("message_start_timestamp", _TIMESTAMP),
        bigquery.SchemaField("message_end_timestamp", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("external_source_id", _STRING),
        bigquery.SchemaField("modality", _STRING),
    ]),

    # Staging das 4 acima — desde 2026-09-08, write_mode='merge' via modo janela
    # (ver utils/janela.py e flow.py): a janela rolante de 1h recaptura
    # o mesmo registro de propósito a cada tick, então precisa de staging+MERGE
    # em vez de append puro (que duplicaria a cada sobreposição).
    "ai_agent_session_staging": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("related_messaging_session_id", _STRING),
        bigquery.SchemaField("ai_agent_channel_type", _STRING),
        bigquery.SchemaField("ai_agent_session_end_type", _STRING),
        bigquery.SchemaField("session_owner_id", _STRING),
        bigquery.SchemaField("session_owner_object", _STRING),
        bigquery.SchemaField("individual_id", _STRING),
        bigquery.SchemaField("previous_session_id", _STRING),
        bigquery.SchemaField("start_timestamp", _TIMESTAMP),
        bigquery.SchemaField("end_timestamp", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("external_source_id", _STRING),
        bigquery.SchemaField("variable_text", _STRING),
    ]),
    "ai_agent_interaction_staging": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("ai_agent_session_id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_type", _STRING),
        bigquery.SchemaField("topic_api_name", _STRING),
        bigquery.SchemaField("session_owner_id", _STRING),
        bigquery.SchemaField("session_owner_object", _STRING),
        bigquery.SchemaField("individual_id", _STRING),
        bigquery.SchemaField("telemetry_trace_id", _STRING),
        bigquery.SchemaField("telemetry_trace_span_id", _STRING),
        bigquery.SchemaField("prev_interaction_id", _STRING),
        bigquery.SchemaField("start_timestamp", _TIMESTAMP),
        bigquery.SchemaField("end_timestamp", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("external_source_id", _STRING),
        bigquery.SchemaField("attribute_text", _STRING),
    ]),
    "ai_agent_interaction_step_staging": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_step_type", _STRING),
        bigquery.SchemaField("name", _STRING),
        bigquery.SchemaField("telemetry_trace_span_id", _STRING),
        bigquery.SchemaField("gen_ai_gateway_request_id", _STRING),
        bigquery.SchemaField("gen_ai_gateway_response_id", _STRING),
        bigquery.SchemaField("generation_id", _STRING),
        bigquery.SchemaField("prev_step_id", _STRING),
        bigquery.SchemaField("start_timestamp", _TIMESTAMP),
        bigquery.SchemaField("end_timestamp", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("external_source_id", _STRING),
        bigquery.SchemaField("pre_step_variable_text", _STRING),
        bigquery.SchemaField("post_step_variable_text", _STRING),
        bigquery.SchemaField("attribute_text", _STRING),
        bigquery.SchemaField("error_message_text", _STRING),
        bigquery.SchemaField("sub_type", _STRING),
        bigquery.SchemaField("output_value_text", _STRING),
    ]),
    "ai_agent_interaction_message_staging": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_id", _STRING),
        bigquery.SchemaField("ai_agent_session_id", _STRING),
        bigquery.SchemaField("ai_agent_session_participant_id", _STRING),
        bigquery.SchemaField("ai_agent_interaction_message_type", _STRING),
        bigquery.SchemaField("ai_agent_interaction_msg_content_type", _STRING),
        bigquery.SchemaField("session_owner_id", _STRING),
        bigquery.SchemaField("individual_id", _STRING),
        bigquery.SchemaField("parent_message_id", _STRING),
        bigquery.SchemaField("content_text", _STRING),
        bigquery.SchemaField("message_sent_timestamp", _TIMESTAMP),
        bigquery.SchemaField("message_start_timestamp", _TIMESTAMP),
        bigquery.SchemaField("message_end_timestamp", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("external_source_id", _STRING),
        bigquery.SchemaField("modality", _STRING),
    ]),

    # --- Messaging ---
    "messaging_end_user": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("name", _STRING),
        bigquery.SchemaField("messaging_channel_id", _STRING),
        bigquery.SchemaField("message_type", _STRING),
        bigquery.SchemaField("messaging_platform_key", _STRING),
        bigquery.SchemaField("locale", _STRING),
        bigquery.SchemaField("iso_country_code", _STRING),
        bigquery.SchemaField("messaging_consent_status", _STRING),
        bigquery.SchemaField("is_fully_opted_in", _BOOL),
        bigquery.SchemaField("messaging_external_user_key", _STRING),
        bigquery.SchemaField("created_date", _TIMESTAMP),
        bigquery.SchemaField("last_modified_date", _TIMESTAMP),
    ]),
    "messaging_session": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("conversation_id", _STRING),
        bigquery.SchemaField("status", _STRING),
        bigquery.SchemaField("start_time", _TIMESTAMP),
        bigquery.SchemaField("end_time", _TIMESTAMP),
        bigquery.SchemaField("messaging_channel_id", _STRING),
        bigquery.SchemaField("messaging_end_user_id", _STRING),
        bigquery.SchemaField("origin", _STRING),
        bigquery.SchemaField("created_date", _TIMESTAMP),
        bigquery.SchemaField("last_modified_date", _TIMESTAMP),
    ]),
    # Staging das duas acima — write_mode='merge' (ver flow.py): carrega aqui via
    # load_chunk_to_staging, depois MERGE pra tabela final via merge_staging_to_target
    # (mesmo padrão de telemetry_trace_span_staging). Substituiu write_mode='replace',
    # que apagava a partição do dia inteiro a cada execução — seguro rodando 1x/dia,
    # mas destrutivo com o schedule de 15 em 15min (cada run apagava o que as runs
    # anteriores do mesmo dia já tinham carregado).
    "messaging_end_user_staging": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("name", _STRING),
        bigquery.SchemaField("messaging_channel_id", _STRING),
        bigquery.SchemaField("message_type", _STRING),
        bigquery.SchemaField("messaging_platform_key", _STRING),
        bigquery.SchemaField("locale", _STRING),
        bigquery.SchemaField("iso_country_code", _STRING),
        bigquery.SchemaField("messaging_consent_status", _STRING),
        bigquery.SchemaField("is_fully_opted_in", _BOOL),
        bigquery.SchemaField("messaging_external_user_key", _STRING),
        bigquery.SchemaField("created_date", _TIMESTAMP),
        bigquery.SchemaField("last_modified_date", _TIMESTAMP),
    ]),
    "messaging_session_staging": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("conversation_id", _STRING),
        bigquery.SchemaField("status", _STRING),
        bigquery.SchemaField("start_time", _TIMESTAMP),
        bigquery.SchemaField("end_time", _TIMESTAMP),
        bigquery.SchemaField("messaging_channel_id", _STRING),
        bigquery.SchemaField("messaging_end_user_id", _STRING),
        bigquery.SchemaField("origin", _STRING),
        bigquery.SchemaField("created_date", _TIMESTAMP),
        bigquery.SchemaField("last_modified_date", _TIMESTAMP),
    ]),
    "conversation_entry": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("conversation_id", _STRING),
        bigquery.SchemaField("conversation_entry_type", _STRING),
        bigquery.SchemaField("conversation_entry_visibility_type", _STRING),
        bigquery.SchemaField("engagement_participant_id", _STRING),
        bigquery.SchemaField("payload_text", _STRING),
        bigquery.SchemaField("language", _STRING),
        bigquery.SchemaField("duration_seconds_count", _FLOAT64),
        bigquery.SchemaField("version_number", _STRING),
        bigquery.SchemaField("external_record_id", _STRING),
        bigquery.SchemaField("client_date_time", _TIMESTAMP),
        bigquery.SchemaField("transcripted_date_time", _TIMESTAMP),
        bigquery.SchemaField("created_date", _TIMESTAMP),
        bigquery.SchemaField("last_modified_date", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("kq_id", _STRING),
    ]),
    "conversation_entry_staging": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("conversation_id", _STRING),
        bigquery.SchemaField("conversation_entry_type", _STRING),
        bigquery.SchemaField("conversation_entry_visibility_type", _STRING),
        bigquery.SchemaField("engagement_participant_id", _STRING),
        bigquery.SchemaField("payload_text", _STRING),
        bigquery.SchemaField("language", _STRING),
        bigquery.SchemaField("duration_seconds_count", _FLOAT64),
        bigquery.SchemaField("version_number", _STRING),
        bigquery.SchemaField("external_record_id", _STRING),
        bigquery.SchemaField("client_date_time", _TIMESTAMP),
        bigquery.SchemaField("transcripted_date_time", _TIMESTAMP),
        bigquery.SchemaField("created_date", _TIMESTAMP),
        bigquery.SchemaField("last_modified_date", _TIMESTAMP),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("kq_id", _STRING),
    ]),

    # --- Tracing ---
    "telemetry_trace_span": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("telemetry_trace", _STRING),
        bigquery.SchemaField("telemetry_parent_span_id", _STRING),
        bigquery.SchemaField("operation_name", _STRING),
        bigquery.SchemaField("span_kind", _STRING),
        bigquery.SchemaField("start_date_time", _TIMESTAMP),
        bigquery.SchemaField("end_date_time", _TIMESTAMP),
        bigquery.SchemaField("duration_number", _FLOAT64),
        bigquery.SchemaField("status_code", _STRING),
        bigquery.SchemaField("service_name", _STRING),
        bigquery.SchemaField("telemetry_span_attribute_text", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("kq_id", _STRING),
    ]),
    "telemetry_trace_span_staging": _base_fields([
        bigquery.SchemaField("id", _STRING),
        bigquery.SchemaField("telemetry_trace", _STRING),
        bigquery.SchemaField("telemetry_parent_span_id", _STRING),
        bigquery.SchemaField("operation_name", _STRING),
        bigquery.SchemaField("span_kind", _STRING),
        bigquery.SchemaField("start_date_time", _TIMESTAMP),
        bigquery.SchemaField("end_date_time", _TIMESTAMP),
        bigquery.SchemaField("duration_number", _FLOAT64),
        bigquery.SchemaField("status_code", _STRING),
        bigquery.SchemaField("service_name", _STRING),
        bigquery.SchemaField("telemetry_span_attribute_text", _STRING),
        bigquery.SchemaField("data_source_id", _STRING),
        bigquery.SchemaField("data_source_object_id", _STRING),
        bigquery.SchemaField("internal_organization_id", _STRING),
        bigquery.SchemaField("kq_id", _STRING),
    ]),

    # --- Eventos WhatsApp ---
    "messaging_events_whatsapp": _base_fields(list(_MESSAGING_EVENTS_WHATSAPP_FIELDS)),
    "messaging_events_whatsapp_staging": _base_fields(list(_MESSAGING_EVENTS_WHATSAPP_FIELDS)),
}

# Tabelas com particionamento + clustering
PARTITIONED_TABLES: dict[str, list[str]] = {
    "ai_agent_session": ["id"],
    "ai_agent_interaction": ["id", "ai_agent_session_id"],
    "ai_agent_interaction_step": ["id", "ai_agent_interaction_id"],
    "ai_agent_interaction_message": ["id", "ai_agent_interaction_id"],
    "messaging_end_user": ["id"],
    "messaging_session": ["id"],
    "conversation_entry": ["id"],
    "telemetry_trace_span": ["id"],
    "messaging_events_whatsapp": ["event_id"],
    # telemetry_trace_span_staging, messaging_end_user_staging, messaging_session_staging:
    # sem particionamento (staging tables)
}

