[project]
name = "rj_cvl__osinfo_mongo"
version = "0.1.0"
description = "Download and reconstruct PDFs from OSINFO MongoDB, partitioned by mes_envio, into GCS."
dependencies = [
    "prefect_rj_iplanrio",
    "pymongo==3.13.0",
    "tenacity>=9.1.4",
]

[tool.uv.sources]
prefect_rj_iplanrio = { workspace = true }
